import { cva } from 'class-variance-authority';

export const buttonVariants = cva(
  [
    // Base styles
    'inline-flex items-center justify-center',
    'whitespace-nowrap font-medium',
    'disabled:pointer-events-none disabled:opacity-50',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
    'active:scale-[0.98]',
    // Icon styles
    '[&_svg]:pointer-events-none [&_svg:not([class*="size-"])]:size-4',
    '[&_svg]:shrink-0',
    'z-10', // Base z-index for proper layering
  ],
  {
    variants: {
      variant: {
        default: [
          'bg-primary text-primary-foreground shadow-sm',
          'hover:bg-primary/90 hover:shadow-md',
          'focus-visible:ring-primary/20',
        ],
        destructive: [
          'bg-destructive text-destructive-foreground shadow-sm',
          'hover:bg-destructive/90 hover:shadow-md',
          'focus-visible:ring-destructive/20',
        ],
        outline: [
          'border border-input bg-background',
          'hover:bg-accent hover:text-accent-foreground hover:shadow-sm',
          'focus-visible:ring-ring/20',
        ],
        secondary: [
          'bg-secondary text-secondary-foreground shadow-sm',
          'hover:bg-secondary/80 hover:shadow-md',
          'focus-visible:ring-secondary/20',
        ],
        ghost: [
          'hover:bg-accent hover:text-accent-foreground',
          'focus-visible:ring-ring/20',
        ],
        link: [
          'text-primary underline-offset-4',
          'hover:underline hover:text-primary/80',
          'focus-visible:ring-ring/20',
        ],
        success: [
          'bg-success-600 text-white shadow-sm',
          'hover:bg-success-700 hover:shadow-md',
          'focus-visible:ring-success-500/20',
        ],
        warning: [
          'bg-warning-600 text-white shadow-sm',
          'hover:bg-warning-700 hover:shadow-md',
          'focus-visible:ring-warning-500/20',
        ],
        info: [
          'bg-info-600 text-white shadow-sm',
          'hover:bg-info-700 hover:shadow-md',
          'focus-visible:ring-info-500/20',
        ],
      },
      size: {
        xs: 'h-6 px-2 text-xs gap-1 has-[>svg]:px-1.5',
        sm: 'h-8 px-3 text-sm gap-1.5 has-[>svg]:px-2.5',
        md: 'h-9 px-4 py-2 text-base gap-2 has-[>svg]:px-3',
        lg: 'h-10 px-6 text-lg gap-2 has-[>svg]:px-4',
        xl: 'h-12 px-8 text-xl gap-2 has-[>svg]:px-6',
        icon: {
          xs: 'size-6 p-0',
          sm: 'size-8 p-0',
          md: 'size-9 p-0',
          lg: 'size-10 p-0',
          xl: 'size-12 p-0',
        },
      },
      spacing: {
        none: 'gap-0',
        sm: 'gap-1',
        md: 'gap-2',
        lg: 'gap-3',
        xl: 'gap-4',
      },
      padding: {
        none: 'p-0',
        sm: 'px-2 py-1',
        md: 'px-4 py-2',
        lg: 'px-6 py-3',
        xl: 'px-8 py-4',
      },
      margin: {
        none: 'm-0',
        sm: 'm-1',
        md: 'm-2',
        lg: 'm-3',
        xl: 'm-4',
      },
      motion: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        slowest: 'transition-all duration-slowest ease-smooth',
      },
      transition: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        colors: 'transition-colors duration-normal ease-smooth',
        transform: 'transition-transform duration-fast ease-smooth',
        opacity: 'transition-opacity duration-normal ease-smooth',
        shadow: 'transition-shadow duration-normal ease-smooth',
      },
      layout: {
        flex: 'inline-flex',
        grid: 'inline-grid',
        block: 'block',
        inline: 'inline',
      },
      flexDirection: {
        row: 'flex-row',
        col: 'flex-col',
        rowReverse: 'flex-row-reverse',
        colReverse: 'flex-col-reverse',
      },
      flexJustify: {
        start: 'justify-start',
        center: 'justify-center',
        end: 'justify-end',
        between: 'justify-between',
        around: 'justify-around',
        evenly: 'justify-evenly',
      },
      flexAlign: {
        start: 'items-start',
        center: 'items-center',
        end: 'items-end',
        stretch: 'items-stretch',
        baseline: 'items-baseline',
      },
      flexWrap: {
        nowrap: 'flex-nowrap',
        wrap: 'flex-wrap',
        wrapReverse: 'flex-wrap-reverse',
      },
      gridColumns: {
        1: 'grid-cols-1',
        2: 'grid-cols-2',
        3: 'grid-cols-3',
        4: 'grid-cols-4',
        5: 'grid-cols-5',
        6: 'grid-cols-6',
        12: 'grid-cols-12',
      },
      gridGap: {
        none: 'gap-grid-none',
        sm: 'gap-grid-sm',
        md: 'gap-grid-md',
        lg: 'gap-grid-lg',
        xl: 'gap-grid-xl',
      },
      borderWidth: {
        none: 'border-0',
        thin: 'border border-thin',
        base: 'border border-base',
        thick: 'border border-thick',
        extra: 'border border-extra',
      },
      borderRadius: {
        none: 'rounded-none',
        sm: 'rounded-sm',
        md: 'rounded-md',
        lg: 'rounded-lg',
        xl: 'rounded-xl',
        '2xl': 'rounded-2xl',
        '3xl': 'rounded-3xl',
        full: 'rounded-full',
      },
      shadow: {
        none: 'shadow-none',
        sm: 'shadow-sm',
        base: 'shadow-base',
        md: 'shadow-md',
        lg: 'shadow-lg',
        xl: 'shadow-xl',
        '2xl': 'shadow-2xl',
        inner: 'shadow-inner',
        card: 'shadow-card',
        button: 'shadow-button',
        modal: 'shadow-modal',
        dropdown: 'shadow-dropdown',
        hover: 'shadow-hover',
        active: 'shadow-active',
        focus: 'shadow-focus',
        glow: 'shadow-glow',
        error: 'shadow-error',
        success: 'shadow-success',
      },
      loading: {
        true: 'pointer-events-none opacity-75',
        false: '',
      },
      elevation: {
        none: '',
        low: 'z-10',
        medium: 'z-20',
        high: 'z-30',
        overlay: 'z-dropdown',
        modal: 'z-modal',
        tooltip: 'z-tooltip',
      },
    },
    compoundVariants: [
      {
        size: 'icon',
        className: 'aspect-square',
      },
    ],
    defaultVariants: {
      variant: 'default',
      size: 'md',
      spacing: 'md',
      padding: 'md',
      margin: 'none',
      motion: 'normal',
      transition: 'normal',
      layout: 'flex',
      flexDirection: 'row',
      flexJustify: 'center',
      flexAlign: 'center',
      flexWrap: 'nowrap',
      gridColumns: 1,
      gridGap: 'md',
      borderWidth: 'none',
      borderRadius: 'md',
      shadow: 'button',
      loading: false,
      elevation: 'low',
    },
  }
);
