# Netlify Configuration for Storybook Deployment

[build]
  base = "frontend"
  command = "pnpm install --frozen-lockfile && pnpm run storybook:build:netlify"
  publish = "storybook-static"

  [build.environment]
    NODE_VERSION = "20"
    NODE_OPTIONS = "--max-old-space-size=8192"
    NODE_ENV = "production"
    # Skip unnecessary npm operations
    NPM_CONFIG_AUDIT = "false"
    NPM_CONFIG_FUND = "false"
    NPM_CONFIG_OPTIONAL = "true"
    NPM_CONFIG_PROGRESS = "false"
    NPM_CONFIG_UPDATE_NOTIFIER = "false"
    NPM_CONFIG_LOGLEVEL = "error"
    # Build optimizations
    SKIP_PREFLIGHT_CHECK = "true"
    CI = "true"

# Build optimizations
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

# SPA routing for Storybook
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:; frame-src 'self';"

# Optimized caching for Storybook assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Environment-specific configs
[context.production]
  command = "pnpm install --frozen-lockfile && pnpm run storybook:build:netlify"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "pnpm install --frozen-lockfile && pnpm run storybook:build:netlify"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

[context.branch-deploy]
  command = "pnpm install --frozen-lockfile && pnpm run storybook:build:netlify"
  [context.branch-deploy.environment]
    NODE_ENV = "production"

# Local dev config for Storybook
[dev]
  command = "pnpm run storybook"
  port = 6006
  targetPort = 6006
  autoLaunch = false
