/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  // Include Storybook files so classes used only in stories/preview are generated
  content: [
    './src/**/*.{ts,tsx,js,jsx,mdx}',
    './index.html',
    './.storybook/**/*.{ts,tsx,js,jsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'var(--colors-border)',
        input: 'var(--colors-input)',
        ring: 'var(--colors-ring)',
        background: 'var(--colors-background)',
        foreground: 'var(--colors-foreground)',
        // Shadcn-style semantic color pairs used across components
        card: {
          DEFAULT: 'var(--colors-background)',
          foreground: 'var(--colors-foreground)',
        },
        popover: {
          DEFAULT: 'var(--colors-background)',
          foreground: 'var(--colors-foreground)',
        },
        primary: {
          50: 'var(--colors-primary-50)',
          100: 'var(--colors-primary-100)',
          200: 'var(--colors-primary-200)',
          300: 'var(--colors-primary-300)',
          400: 'var(--colors-primary-400)',
          500: 'var(--colors-primary-500)',
          600: 'var(--colors-primary-600)',
          700: 'var(--colors-primary-700)',
          800: 'var(--colors-primary-800)',
          900: 'var(--colors-primary-900)',
          950: 'var(--colors-primary-950)',
          DEFAULT: 'var(--colors-primary-500)',
          foreground: 'var(--colors-foreground)',
        },
        secondary: {
          50: 'var(--colors-secondary-50)',
          100: 'var(--colors-secondary-100)',
          200: 'var(--colors-secondary-200)',
          300: 'var(--colors-secondary-300)',
          400: 'var(--colors-secondary-400)',
          500: 'var(--colors-secondary-500)',
          600: 'var(--colors-secondary-600)',
          700: 'var(--colors-secondary-700)',
          800: 'var(--colors-secondary-800)',
          900: 'var(--colors-secondary-900)',
          950: 'var(--colors-secondary-950)',
          DEFAULT: 'var(--colors-secondary-500)',
          foreground: 'var(--colors-foreground)',
        },
        destructive: {
          50: 'var(--colors-destructive-50)',
          100: 'var(--colors-destructive-100)',
          200: 'var(--colors-destructive-200)',
          300: 'var(--colors-destructive-300)',
          400: 'var(--colors-destructive-400)',
          500: 'var(--colors-destructive-500)',
          600: 'var(--colors-destructive-600)',
          700: 'var(--colors-destructive-700)',
          800: 'var(--colors-destructive-800)',
          900: 'var(--colors-destructive-900)',
          950: 'var(--colors-destructive-950)',
          DEFAULT: 'var(--colors-destructive-500)',
          foreground: 'var(--colors-foreground)',
        },
        muted: {
          50: 'var(--colors-muted-50)',
          100: 'var(--colors-muted-100)',
          200: 'var(--colors-muted-200)',
          300: 'var(--colors-muted-300)',
          400: 'var(--colors-muted-400)',
          500: 'var(--colors-muted-500)',
          600: 'var(--colors-muted-600)',
          700: 'var(--colors-muted-700)',
          800: 'var(--colors-muted-800)',
          900: 'var(--colors-muted-900)',
          950: 'var(--colors-muted-950)',
          DEFAULT: 'var(--colors-muted-500)',
          foreground: 'var(--colors-foreground)',
        },
        accent: {
          50: 'var(--colors-accent-50)',
          100: 'var(--colors-accent-100)',
          200: 'var(--colors-accent-200)',
          300: 'var(--colors-accent-300)',
          400: 'var(--colors-accent-400)',
          500: 'var(--colors-accent-500)',
          600: 'var(--colors-accent-600)',
          700: 'var(--colors-accent-700)',
          800: 'var(--colors-accent-800)',
          900: 'var(--colors-accent-900)',
          950: 'var(--colors-accent-950)',
          DEFAULT: 'var(--colors-accent-500)',
          foreground: 'var(--colors-foreground)',
        },
        success: {
          50: 'var(--colors-success-50)',
          100: 'var(--colors-success-100)',
          200: 'var(--colors-success-200)',
          300: 'var(--colors-success-300)',
          400: 'var(--colors-success-400)',
          500: 'var(--colors-success-500)',
          600: 'var(--colors-success-600)',
          700: 'var(--colors-success-700)',
          800: 'var(--colors-success-800)',
          900: 'var(--colors-success-900)',
          950: 'var(--colors-success-950)',
          DEFAULT: 'var(--colors-success-500)',
          foreground: 'var(--colors-foreground)',
        },
        warning: {
          50: 'var(--colors-warning-50)',
          100: 'var(--colors-warning-100)',
          200: 'var(--colors-warning-200)',
          300: 'var(--colors-warning-300)',
          400: 'var(--colors-warning-400)',
          500: 'var(--colors-warning-500)',
          600: 'var(--colors-warning-600)',
          700: 'var(--colors-warning-700)',
          800: 'var(--colors-warning-800)',
          900: 'var(--colors-warning-900)',
          950: 'var(--colors-warning-950)',
          DEFAULT: 'var(--colors-warning-500)',
          foreground: 'var(--colors-foreground)',
        },
        info: {
          50: 'var(--colors-info-50)',
          100: 'var(--colors-info-100)',
          200: 'var(--colors-info-200)',
          300: 'var(--colors-info-300)',
          400: 'var(--colors-info-400)',
          500: 'var(--colors-info-500)',
          600: 'var(--colors-info-600)',
          700: 'var(--colors-info-700)',
          800: 'var(--colors-info-800)',
          900: 'var(--colors-info-900)',
          950: 'var(--colors-info-950)',
          DEFAULT: 'var(--colors-info-500)',
          foreground: 'var(--colors-foreground)',
        },
        surface: 'var(--colors-surface)',
        'on-surface': 'var(--colors-onSurface)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        base: 'var(--border-radius-base)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        '2xl': 'var(--border-radius-2xl)',
        '3xl': 'var(--border-radius-3xl)',
        full: 'var(--border-radius-full)',
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
        32: 'var(--spacing-32)',
        40: 'var(--spacing-40)',
        48: 'var(--spacing-48)',
        56: 'var(--spacing-56)',
        64: 'var(--spacing-64)',
      },
      boxShadow: {
        sm: 'var(--shadows-sm)',
        base: 'var(--shadows-base)',
        md: 'var(--shadows-md)',
        lg: 'var(--shadows-lg)',
        xl: 'var(--shadows-xl)',
        '2xl': 'var(--shadows-2xl)',
      },
      fontFamily: {
        sans: 'var(--typography-font-family-sans)',
        mono: 'var(--typography-font-family-mono)',
      },
      fontSize: {
        xs: 'var(--typography-font-size-xs)',
        sm: 'var(--typography-font-size-sm)',
        base: 'var(--typography-font-size-base)',
        lg: 'var(--typography-font-size-lg)',
        xl: 'var(--typography-font-size-xl)',
        '2xl': 'var(--typography-font-size-2xl)',
        '3xl': 'var(--typography-font-size-3xl)',
        '4xl': 'var(--typography-font-size-4xl)',
        '5xl': 'var(--typography-font-size-5xl)',
        '6xl': 'var(--typography-font-size-6xl)',
      },
      fontWeight: {
        light: 'var(--typography-font-weight-light)',
        normal: 'var(--typography-font-weight-normal)',
        medium: 'var(--typography-font-weight-medium)',
        semibold: 'var(--typography-font-weight-semibold)',
        bold: 'var(--typography-font-weight-bold)',
        extrabold: 'var(--typography-font-weight-extrabold)',
        black: 'var(--typography-font-weight-black)',
      },
      screens: {
        sm: 'var(--breakpoints-sm)',
        md: 'var(--breakpoints-md)',
        lg: 'var(--breakpoints-lg)',
        xl: 'var(--breakpoints-xl)',
        '2xl': 'var(--breakpoints-2xl)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
