[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[providers]
python = {}

[phases.setup]
nixpkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"