[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend build completed'"]

[start]
cmd = "python main.py"

[variables]
NODE_ENV = "production" 