[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

providers = ["python"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"