import { cva } from 'class-variance-authority';

export const textVariants = cva(
  [
    // Base styles
    'leading-normal',
  ],
  {
    variants: {
      variant: {
        body: 'font-normal',
        caption: 'text-xs font-medium uppercase tracking-wide',
        overline: 'text-xs font-semibold uppercase tracking-widest',
        h1: 'font-bold tracking-tight',
        h2: 'font-semibold tracking-tight',
        h3: 'font-semibold',
        h4: 'font-semibold',
        h5: 'font-medium',
        h6: 'font-medium',
        headline: 'font-bold tracking-tight',
        subheadline: 'font-semibold tracking-tight',
        title: 'font-semibold',
        subtitle: 'font-medium',
        elegant: 'font-light tracking-wide',
        code: 'font-mono',
      },
      size: {
        xs: 'text-xs',
        sm: 'text-sm',
        md: 'text-base',
        lg: 'text-lg',
        xl: 'text-xl',
        '2xl': 'text-2xl',
        '3xl': 'text-3xl',
        '4xl': 'text-4xl',
        '5xl': 'text-5xl',
        '6xl': 'text-6xl',
        '7xl': 'text-7xl',
        '8xl': 'text-8xl',
        '9xl': 'text-9xl',
      },
      weight: {
        thin: 'font-thin',
        extralight: 'font-extralight',
        light: 'font-light',
        normal: 'font-normal',
        medium: 'font-medium',
        semibold: 'font-semibold',
        bold: 'font-bold',
        extrabold: 'font-extrabold',
        black: 'font-black',
      },
      color: {
        default: 'text-foreground',
        muted: 'text-muted-foreground',
        primary: 'text-primary',
        secondary: 'text-secondary-foreground',
        destructive: 'text-destructive',
        success: 'text-success-600',
        warning: 'text-warning-600',
        info: 'text-info-600',
      },
      align: {
        left: 'text-left',
        center: 'text-center',
        right: 'text-right',
        justify: 'text-justify',
      },
      truncate: {
        true: 'truncate',
        false: '',
      },
      fontFamily: {
        sans: 'font-sans',
        serif: 'font-serif',
        display: 'font-display',
        mono: 'font-mono',
        elegant: 'font-elegant',
        modern: 'font-modern',
      },
      lineHeight: {
        none: 'leading-none',
        tight: 'leading-tight',
        snug: 'leading-snug',
        normal: 'leading-normal',
        relaxed: 'leading-relaxed',
        loose: 'leading-loose',
        'extra-loose': 'leading-extra-loose',
      },
      letterSpacing: {
        tighter: 'tracking-tighter',
        tight: 'tracking-tight',
        normal: 'tracking-normal',
        wide: 'tracking-wide',
        wider: 'tracking-wider',
        widest: 'tracking-widest',
        'extra-wide': 'tracking-extra-wide',
      },
    },
    compoundVariants: [
      {
        variant: 'h1',
        size: '4xl',
        className: 'scroll-m-20',
      },
      {
        variant: 'h2',
        size: '3xl',
        className: 'scroll-m-20',
      },
      {
        variant: 'h3',
        size: '2xl',
        className: 'scroll-m-20',
      },
      {
        variant: 'h4',
        size: 'xl',
        className: 'scroll-m-20',
      },
      {
        variant: 'h5',
        size: 'lg',
        className: 'scroll-m-20',
      },
      {
        variant: 'h6',
        size: 'md',
        className: 'scroll-m-20',
      },
      // Typography foundation compliance variants
      {
        variant: 'headline',
        size: '4xl',
        weight: 'bold',
        lineHeight: 'tight',
        letterSpacing: 'tight',
        fontFamily: 'display',
        className: 'scroll-m-20',
      },
      {
        variant: 'subheadline',
        size: '2xl',
        weight: 'semibold',
        lineHeight: 'snug',
        letterSpacing: 'normal',
        fontFamily: 'display',
        className: 'scroll-m-20',
      },
      {
        variant: 'title',
        size: 'xl',
        weight: 'semibold',
        lineHeight: 'snug',
        letterSpacing: 'normal',
        fontFamily: 'sans',
        className: 'scroll-m-20',
      },
      {
        variant: 'subtitle',
        size: 'lg',
        weight: 'medium',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        fontFamily: 'sans',
      },
      {
        variant: 'body',
        size: 'base',
        weight: 'normal',
        lineHeight: 'relaxed',
        letterSpacing: 'normal',
        fontFamily: 'sans',
      },
      {
        variant: 'caption',
        size: 'sm',
        weight: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'wide',
        fontFamily: 'sans',
      },
      {
        variant: 'elegant',
        size: 'lg',
        weight: 'light',
        lineHeight: 'relaxed',
        letterSpacing: 'wide',
        fontFamily: 'elegant',
      },
      {
        variant: 'code',
        size: 'sm',
        weight: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        fontFamily: 'mono',
      },
    ],
    defaultVariants: {
      variant: 'body',
      size: 'md',
      weight: 'normal',
      color: 'default',
      align: 'left',
      truncate: false,
      fontFamily: 'sans',
      lineHeight: 'normal',
      letterSpacing: 'normal',
    },
  }
);
