// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-tokens.ts from src/design-system/tokens.json

export const tokens = {
  'colors': {
    'primary': {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
      950: '#172554'
    },
    'secondary': {
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      400: '#94a3b8',
      500: '#64748b',
      600: '#475569',
      700: '#334155',
      800: '#1e293b',
      900: '#0f172a',
      950: '#020617'
    },
    'accent': {
      50: '#f0fdf4',
      100: '#dcfce7',
      200: '#bbf7d0',
      300: '#86efac',
      400: '#4ade80',
      500: '#22c55e',
      600: '#16a34a',
      700: '#15803d',
      800: '#166534',
      900: '#14532d',
      950: '#052e16'
    },
    'destructive': {
      50: '#fef2f2',
      100: '#fee2e2',
      200: '#fecaca',
      300: '#fca5a5',
      400: '#f87171',
      500: '#ef4444',
      600: '#dc2626',
      700: '#b91c1c',
      800: '#991b1b',
      900: '#7f1d1d',
      950: '#450a0a'
    },
    'success': '#22c55e',
    'warning': '#f59e0b',
    'info': '#3b82f6',
    'muted': {
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      400: '#94a3b8',
      500: '#64748b',
      600: '#475569',
      700: '#334155',
      800: '#1e293b',
      900: '#0f172a',
      950: '#020617'
    },
    'hover': {
      'primary': '#2563eb',
      'secondary': '#475569',
      'accent': '#16a34a',
      'destructive': '#dc2626',
      'success': '#16a34a',
      'warning': '#d97706',
      'info': '#2563eb'
    },
    'active': {
      'primary': '#1d4ed8',
      'secondary': '#334155',
      'accent': '#15803d',
      'destructive': '#b91c1c',
      'success': '#15803d',
      'warning': '#b45309',
      'info': '#1d4ed8'
    },
    'focus': {
      'primary': '#3b82f6',
      'secondary': '#64748b',
      'accent': '#22c55e',
      'destructive': '#ef4444',
      'success': '#22c55e',
      'warning': '#f59e0b',
      'info': '#3b82f6'
    },
    'border': '#e2e8f0',
    'input': '#ffffff',
    'ring': '#3b82f6',
    'background': '#ffffff',
    'foreground': '#0f172a',
    'surface': '#ffffff',
    'onSurface': '#0f172a',
    'danger': '#ef4444'
  },
  'typography': {
    'fontSize': {
      'xs': '0.75rem',
      'sm': '0.875rem',
      'base': '1rem',
      'lg': '1.125rem',
      'xl': '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem'
    },
    'fontFamily': {
      'sans': [
        'Inter',
        'system-ui',
        'sans-serif'
      ],
      'mono': [
        'JetBrains Mono',
        'monospace'
      ]
    },
    'fontWeight': {
      'light': '300',
      'normal': '400',
      'medium': '500',
      'semibold': '600',
      'bold': '700',
      'extrabold': '800'
    },
    'letterSpacing': {
      'tighter': '-0.05em',
      'tight': '-0.025em',
      'normal': '0',
      'wide': '0.025em',
      'wider': '0.05em',
      'widest': '0.1em'
    },
    'lineHeight': {
      'tight': '1.25',
      'snug': '1.375',
      'normal': '1.5',
      'relaxed': '1.625',
      'loose': '2'
    }
  },
  'spacing': {
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    32: '8rem',
    40: '10rem',
    48: '12rem',
    56: '14rem',
    64: '16rem'
  },
  'borderRadius': {
    'none': '0',
    'sm': '0.125rem',
    'base': '0.25rem',
    'md': '0.375rem',
    'lg': '0.5rem',
    'xl': '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    'full': '9999px'
  },
  'borderWidth': {},
  'shadows': {
    'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    'base': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)'
  },
  'transitions': {},
  'motion': {
    'easing': {
      'linear': 'linear',
      'ease-in': 'ease-in',
      'ease-out': 'ease-out',
      'ease-in-out': 'ease-in-out',
      'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)'
    },
    'duration': {
      'fast': '150ms',
      'normal': '300ms',
      'slow': '500ms',
      'slower': '700ms'
    }
  },
  'zIndex': {
    0: '0',
    10: '10',
    20: '20',
    30: '30',
    40: '40',
    50: '50',
    'auto': 'auto',
    'dropdown': '1000',
    'sticky': '1020',
    'fixed': '1030',
    'modal': '1040',
    'popover': '1050',
    'tooltip': '1060'
  }
} as const;

export const cssVariables = {
  'light': {},
  'dark': {}
} as const;

export const getToken = (path: string) => {
  return path.split('.').reduce((obj: any, key: string) => obj?.[key], tokens);
};

export const getCSSVariable = (name: string) => {
  return `var(${name})`;
};
