// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-tokens.ts from src/design-system/tokens.json

export const tokens = {
  'colors': {
    'primary': {
      50: 'hsl(210, 100%, 98%)',
      500: 'hsl(215, 91%, 65%)',
      700: 'hsl(215, 91%, 43%)'
    },
    'neutral': {
      50: 'hsl(0, 0%, 98%)',
      900: 'hsl(0, 0%, 9%)'
    },
    'success': {
      500: 'hsl(142, 71%, 45%)'
    },
    'warning': {
      500: 'hsl(48, 96%, 53%)'
    },
    'error': {
      500: 'hsl(0, 84%, 60%)'
    }
  },
  'typography': {
    'fontSize': {
      'sm': [
        '0.75rem',
        {
          'lineHeight': '1.125rem'
        }
      ],
      'md': [
        '0.875rem',
        {
          'lineHeight': '1.25rem'
        }
      ],
      'lg': [
        '1rem',
        {
          'lineHeight': '1.5rem'
        }
      ]
    }
  },
  'spacing': {
    'xs': '0.25rem',
    'sm': '0.5rem',
    'md': '0.75rem',
    'lg': '1rem',
    'xl': '1.5rem'
  },
  'borderRadius': {
    'sm': '0.25rem',
    'md': '0.375rem',
    'lg': '0.5rem'
  },
  'shadows': {
    'sm': '0 1px 2px rgba(0,0,0,0.05)',
    'md': '0 2px 8px rgba(0,0,0,0.10)'
  },
  'transitions': {
    'fast': '150ms ease-in-out',
    'normal': '200ms ease-in-out',
    'slow': '300ms ease-in-out'
  },
  'zIndex': {
    'base': 0,
    'dropdown': 1000,
    'modal': 1300,
    'toast': 1500
  }
} as const;

export const cssVariables = {
  'light': {
    '--background': '#ffffff',
    '--foreground': '#0a0a0a',
    '--primary': '#030213',
    '--primary-foreground': '#ffffff'
  },
  'dark': {
    '--background': '#0a0a0a',
    '--foreground': '#ffffff',
    '--primary': '#ffffff',
    '--primary-foreground': '#0a0a0a'
  }
} as const;

export const getToken = (path: string) => {
  return path.split('.').reduce((obj: any, key: string) => obj?.[key], tokens);
};

export const getCSSVariable = (name: string) => {
  return `var(${name})`;
};
