import { cva } from 'class-variance-authority';

export const badgeVariants = cva(
  [
    // Base styles
    'inline-flex items-center justify-center border px-2 py-0.5 text-xs font-medium',
    'w-fit whitespace-nowrap shrink-0 gap-1',
    '[&>svg]:size-3 [&>svg]:pointer-events-none',
    'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
    'overflow-hidden',
    'z-10', // Base z-index for proper layering
  ],
  {
    variants: {
      variant: {
        default: [
          'border-transparent bg-primary text-primary-foreground',
          '[a&]:hover:bg-primary/90',
        ],
        secondary: [
          'border-transparent bg-secondary text-secondary-foreground',
          '[a&]:hover:bg-secondary/90',
        ],
        destructive: [
          'border-transparent bg-destructive text-white',
          '[a&]:hover:bg-destructive/90',
          'focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40',
          'dark:bg-destructive/60',
        ],
        outline: [
          'text-foreground',
          '[a&]:hover:bg-accent [a&]:hover:text-accent-foreground',
        ],
        success: [
          'border-transparent bg-success-600 text-white',
          '[a&]:hover:bg-success-700',
        ],
        warning: [
          'border-transparent bg-warning-600 text-white',
          '[a&]:hover:bg-warning-700',
        ],
        info: [
          'border-transparent bg-info-600 text-white',
          '[a&]:hover:bg-info-700',
        ],
        muted: [
          'border-transparent bg-muted text-muted-foreground',
          '[a&]:hover:bg-muted/90',
        ],
      },
      size: {
        sm: 'px-1.5 py-0.5 text-xs [&>svg]:size-2.5',
        md: 'px-2 py-0.5 text-xs [&>svg]:size-3',
        lg: 'px-2.5 py-1 text-sm [&>svg]:size-3.5',
      },
      spacing: {
        none: 'gap-0',
        sm: 'gap-1',
        md: 'gap-2',
        lg: 'gap-3',
        xl: 'gap-4',
      },
      padding: {
        none: 'p-0',
        sm: 'px-1.5 py-0.5',
        md: 'px-2 py-0.5',
        lg: 'px-3 py-1',
        xl: 'px-4 py-2',
      },
      margin: {
        none: 'm-0',
        sm: 'm-1',
        md: 'm-2',
        lg: 'm-3',
        xl: 'm-4',
      },
      motion: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        slowest: 'transition-all duration-slowest ease-smooth',
      },
      transition: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        colors: 'transition-colors duration-normal ease-smooth',
        transform: 'transition-transform duration-fast ease-smooth',
        opacity: 'transition-opacity duration-normal ease-smooth',
        shadow: 'transition-shadow duration-normal ease-smooth',
      },
      layout: {
        flex: 'inline-flex',
        grid: 'inline-grid',
        block: 'block',
        inline: 'inline',
      },
      flexDirection: {
        row: 'flex-row',
        col: 'flex-col',
        rowReverse: 'flex-row-reverse',
        colReverse: 'flex-col-reverse',
      },
      flexJustify: {
        start: 'justify-start',
        center: 'justify-center',
        end: 'justify-end',
        between: 'justify-between',
        around: 'justify-around',
        evenly: 'justify-evenly',
      },
      flexAlign: {
        start: 'items-start',
        center: 'items-center',
        end: 'items-end',
        stretch: 'items-stretch',
        baseline: 'items-baseline',
      },
      flexWrap: {
        nowrap: 'flex-nowrap',
        wrap: 'flex-wrap',
        wrapReverse: 'flex-wrap-reverse',
      },
      gridColumns: {
        1: 'grid-cols-1',
        2: 'grid-cols-2',
        3: 'grid-cols-3',
        4: 'grid-cols-4',
        5: 'grid-cols-5',
        6: 'grid-cols-6',
        12: 'grid-cols-12',
      },
      gridGap: {
        none: 'gap-grid-none',
        sm: 'gap-grid-sm',
        md: 'gap-grid-md',
        lg: 'gap-grid-lg',
        xl: 'gap-grid-xl',
      },
      borderWidth: {
        none: 'border-0',
        thin: 'border border-thin',
        base: 'border border-base',
        thick: 'border border-thick',
        extra: 'border border-extra',
      },
      borderRadius: {
        none: 'rounded-none',
        sm: 'rounded-sm',
        md: 'rounded-md',
        lg: 'rounded-lg',
        xl: 'rounded-xl',
        '2xl': 'rounded-2xl',
        '3xl': 'rounded-3xl',
        full: 'rounded-full',
      },
      shadow: {
        none: 'shadow-none',
        sm: 'shadow-sm',
        base: 'shadow-base',
        md: 'shadow-md',
        lg: 'shadow-lg',
        xl: 'shadow-xl',
        '2xl': 'shadow-2xl',
        inner: 'shadow-inner',
        card: 'shadow-card',
        button: 'shadow-button',
        modal: 'shadow-modal',
        dropdown: 'shadow-dropdown',
        hover: 'shadow-hover',
        active: 'shadow-active',
        focus: 'shadow-focus',
        glow: 'shadow-glow',
        error: 'shadow-error',
        success: 'shadow-success',
      },
      elevation: {
        none: '',
        low: 'z-10',
        medium: 'z-20',
        high: 'z-30',
        overlay: 'z-dropdown',
        modal: 'z-modal',
        tooltip: 'z-tooltip',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
      spacing: 'sm',
      padding: 'md',
      margin: 'none',
      motion: 'normal',
      transition: 'normal',
      layout: 'flex',
      flexDirection: 'row',
      flexJustify: 'center',
      flexAlign: 'center',
      flexWrap: 'nowrap',
      gridColumns: 1,
      gridGap: 'sm',
      borderWidth: 'thin',
      borderRadius: 'md',
      shadow: 'none',
      elevation: 'low',
    },
  }
);
