import { cva } from 'class-variance-authority';

export const inputVariants = cva(
  [
    // Base styles
    'flex w-full min-w-0 border bg-background',
    'text-base outline-none',
    'file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground',
    'placeholder:text-muted-foreground',
    'selection:bg-primary selection:text-primary-foreground',
    'focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
    'disabled:cursor-not-allowed disabled:opacity-50 disabled:pointer-events-none',
    'md:text-sm',
    'z-10', // Base z-index for proper layering
    // Autofill styling for better design system compliance
    '[&:-webkit-autofill]:bg-background [&:-webkit-autofill]:text-foreground',
    '[&:-webkit-autofill]:shadow-[0_0_0_30px_hsl(var(--background))_inset]',
    '[&:-webkit-autofill]:border-ring [&:-webkit-autofill]:ring-2 [&:-webkit-autofill]:ring-ring [&:-webkit-autofill]:ring-offset-2',
    '[&:-webkit-autofill]:transition-all [&:-webkit-autofill]:duration-normal',
    // Autofill focus states
    '[&:-webkit-autofill:focus]:border-ring [&:-webkit-autofill:focus]:ring-2 [&:-webkit-autofill:focus]:ring-ring [&:-webkit-autofill:focus]:ring-offset-2',
    // Autofill hover states
    '[&:-webkit-autofill:hover]:border-ring',
    // Dark mode autofill support
    'dark:[&:-webkit-autofill]:bg-background dark:[&:-webkit-autofill]:text-foreground',
    'dark:[&:-webkit-autofill]:shadow-[0_0_0_30px_hsl(var(--background))_inset]',
    'dark:[&:-webkit-autofill]:border-ring dark:[&:-webkit-autofill]:ring-2 dark:[&:-webkit-autofill]:ring-ring dark:[&:-webkit-autofill]:ring-offset-2',
  ],
  {
    variants: {
      size: {
        sm: 'h-7 text-sm',
        md: 'h-9 text-base',
        lg: 'h-11 text-lg',
      },
      padding: {
        none: 'p-0',
        sm: 'px-2 py-1',
        md: 'px-3 py-2',
        lg: 'px-4 py-3',
        xl: 'px-6 py-4',
      },
      margin: {
        none: 'm-0',
        sm: 'm-1',
        md: 'm-2',
        lg: 'm-3',
        xl: 'm-4',
      },
      motion: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        slowest: 'transition-all duration-slowest ease-smooth',
      },
      transition: {
        none: 'transition-none',
        fast: 'transition-all duration-fast ease-smooth',
        normal: 'transition-all duration-normal ease-smooth',
        slow: 'transition-all duration-slow ease-smooth',
        slower: 'transition-all duration-slower ease-smooth',
        colors: 'transition-colors duration-normal ease-smooth',
        transform: 'transition-transform duration-fast ease-smooth',
        opacity: 'transition-opacity duration-normal ease-smooth',
        shadow: 'transition-shadow duration-normal ease-smooth',
      },
      layout: {
        flex: 'flex',
        grid: 'grid',
        block: 'block',
        inline: 'inline',
      },
      flexDirection: {
        row: 'flex-row',
        col: 'flex-col',
        rowReverse: 'flex-row-reverse',
        colReverse: 'flex-col-reverse',
      },
      flexJustify: {
        start: 'justify-start',
        center: 'justify-center',
        end: 'justify-end',
        between: 'justify-between',
        around: 'justify-around',
        evenly: 'justify-evenly',
      },
      flexAlign: {
        start: 'items-start',
        center: 'items-center',
        end: 'items-end',
        stretch: 'items-stretch',
        baseline: 'items-baseline',
      },
      flexWrap: {
        nowrap: 'flex-nowrap',
        wrap: 'flex-wrap',
        wrapReverse: 'flex-wrap-reverse',
      },
      gridColumns: {
        1: 'grid-cols-1',
        2: 'grid-cols-2',
        3: 'grid-cols-3',
        4: 'grid-cols-4',
        5: 'grid-cols-5',
        6: 'grid-cols-6',
        12: 'grid-cols-12',
      },
      gridGap: {
        none: 'gap-grid-none',
        sm: 'gap-grid-sm',
        md: 'gap-grid-md',
        lg: 'gap-grid-lg',
        xl: 'gap-grid-xl',
      },
      borderWidth: {
        none: 'border-0',
        thin: 'border border-thin',
        base: 'border border-base',
        thick: 'border border-thick',
        extra: 'border border-extra',
      },
      borderRadius: {
        none: 'rounded-none',
        sm: 'rounded-sm',
        md: 'rounded-md',
        lg: 'rounded-lg',
        xl: 'rounded-xl',
        '2xl': 'rounded-2xl',
        '3xl': 'rounded-3xl',
        full: 'rounded-full',
      },
      shadow: {
        none: 'shadow-none',
        sm: 'shadow-sm',
        base: 'shadow-base',
        md: 'shadow-md',
        lg: 'shadow-lg',
        xl: 'shadow-xl',
        '2xl': 'shadow-2xl',
        inner: 'shadow-inner',
        card: 'shadow-card',
        button: 'shadow-button',
        modal: 'shadow-modal',
        dropdown: 'shadow-dropdown',
        hover: 'shadow-hover',
        active: 'shadow-active',
        focus: 'shadow-focus',
        glow: 'shadow-glow',
        error: 'shadow-error',
        success: 'shadow-success',
      },
      error: {
        true: [
          'border-destructive focus-visible:ring-destructive',
          '[&:-webkit-autofill]:border-destructive [&:-webkit-autofill]:ring-destructive',
          '[&:-webkit-autofill:focus]:border-destructive [&:-webkit-autofill:focus]:ring-destructive',
        ],
        false: 'border-input',
      },
      elevation: {
        none: '',
        low: 'z-10',
        medium: 'z-20',
        high: 'z-30',
        overlay: 'z-dropdown',
        modal: 'z-modal',
        tooltip: 'z-tooltip',
      },
    },
    defaultVariants: {
      size: 'md',
      padding: 'md',
      margin: 'none',
      motion: 'normal',
      transition: 'normal',
      layout: 'block',
      flexDirection: 'row',
      flexJustify: 'start',
      flexAlign: 'stretch',
      flexWrap: 'nowrap',
      gridColumns: 1,
      gridGap: 'none',
      borderWidth: 'thin',
      borderRadius: 'md',
      shadow: 'none',
      error: false,
      elevation: 'low',
    },
  }
);
