name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (optimized for CI)
        working-directory: ./frontend
        run: |
          # Install all dependencies for CI (includes dev tools for linting/testing)
          npm ci --prefer-offline --no-audit --no-fund
          # Verify essential tools are available
          echo "Verifying CI tools..."
          npx eslint --version && echo "✅ ESLint found"
          npx tsc --version && echo "✅ TypeScript found"  
          npx vitest --version && echo "✅ Vitest found"
        env:
          NODE_ENV: production

      - name: Run linting
        working-directory: ./frontend
        run: |
          # Use npx to ensure ESLint is found
          npx eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 100

      - name: Run type checking
        working-directory: ./frontend
        run: |
          # Use npx to ensure TypeScript is found
          npx tsc --noEmit

      - name: Run tests
        working-directory: ./frontend
        run: |
          # Use npx to ensure Vitest is found
          npx vitest run --reporter=verbose
        env:
          NODE_ENV: test

      - name: Build (optimized)
        working-directory: ./frontend
        run: npm run build:netlify:prod
        env:
          NODE_ENV: production
          NODE_OPTIONS: "--max-old-space-size=8192"

  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: finvision_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ~/.cache/pip

      - name: Run linting
        working-directory: ./backend
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        working-directory: ./backend
        env:
          POSTGRES_SERVER: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: finvision_test
          REDIS_URL: redis://localhost:6379
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Test Docker containers
        run: |
          docker-compose up -d
          sleep 30
          curl -f http://localhost:8000/health || exit 1
          docker-compose down
