name: Database Services (PostgreSQL + Redis)

on:
  workflow_call:
    inputs:
      postgres-db:
        description: "PostgreSQL database name"
        required: false
        type: string
        default: "finvision_test"

jobs:
  services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: ${{ inputs.postgres-db }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Database services ready
        run: echo "PostgreSQL and Redis services are ready"
