name: Node.js Setup with pnpm

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "20"
      pnpm-version:
        description: "pnpm version to use"
        required: false
        type: string
        default: "8"
      working-directory:
        description: "Working directory for frontend"
        required: false
        type: string
        default: "./frontend"
      install-deps:
        description: "Whether to install dependencies"
        required: false
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Get pnpm store directory
        if: ${{ inputs.install-deps }}
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        if: ${{ inputs.install-deps }}
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: ${{ inputs.install-deps }}
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile
