name: Storybook CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/storybook.yml'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/storybook.yml'

jobs:
  storybook:
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@36de12bed180fa130ed56a35e7344f2fa7a820ab # v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint:ci || true

      - name: Verify stories coverage
        run: pnpm verify:stories

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Run Storybook tests (a11y/interactions)
        run: pnpm storybook:test:ci

      - name: Publish to Chromatic
        if: env.CHROMATIC_PROJECT_TOKEN != ''
        run: pnpm chromatic --project-token="$CHROMATIC_PROJECT_TOKEN" --exit-zero-on-changes
